### ISSUE TITLE
Admin wrapper for list topic and list partition.

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-client-wasm#1]
Call this with [`FluvioAdmin::list`](https://docs.rs/fluvio/0.8.2/fluvio/struct.FluvioAdmin.html#method.list) a `TopicSpec`.

Currently, the remaining part is to convert `Result<Vec<Metadata<TopicSpec>, Global>, FluvioError>` into a `Vec<String>` in [`src/admin.rs`](https://github.com/infinyon/fluvio-client-wasm/blob/2dc8ede78288c2375b6d429c988d03d2faa1f3af/src/admin.rs#L23).

**Comment by morenol** [comment]
> Currently, the remaining part is to convert Result<Vec<Metadata<TopicSpec>, Global>, FluvioError> into a Vec<String> in src/admin.rs.

I did that in #11, for both topics and partitions. Then I added an additional commit to return a TopicMetadata binding instead in order to have available the number of partitions and the replication factor in the returned object.

**Comment by simlay** [comment]
Closed in #11.
