### ISSUE TITLE
Generated fluvio-client.js uses BigInt64Array

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio-client-wasm#17]
`BigInt64Array` is not supported in Safari, need to find out which library is generating this JS output.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array
Suggests that `DataView` is an alternative to `BigInt64Array`

**Comment by morenol** [comment]
Maybe it is due to: https://github.com/infinyon/fluvio-client-wasm/blob/d3450e98a5cdf06d04787e5bf0be191303d91cd1/src/record.rs#L27

https://rustwasm.github.io/wasm-bindgen/reference/browser-support.html

**Comment by sehz** [comment]
https://stackoverflow.com/questions/63302196/webassembly-i64-primitive-type
