### ISSUE TITLE
Investigate BorrowMutException

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-client-wasm#42]
There are times when you can get an `already borrowed BorrowMutException`. Let's figure out why and what to do to prevent this.

**Comment by nicholastmosher** [comment]
This sounds like the type of error that would happen if you use `RefCell::borrow` and then borrow again while you still hold the reference.

**Comment by morenol** [comment]
> This sounds like the type of error that would happen if you use `RefCell::borrow` and then borrow again while you still hold the reference.

Yes, it looks like we are calling listPartitions and the admin client is already borrowed somewhere

https://github.com/infinyon/fluvio-client-wasm/blob/7bb9c154ed4459d15395f160c0210c3ed72d6df4/src/admin.rs#L29
